name: login_flutter
description: A flutter login model app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.1.2
  intl: ^0.17.0
  http: ^1.2.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.0.6
  cached_network_image: ^3.2.2
  flutter_svg: ^2.0.7
  audioplayers: ^6.4.0
  google_fonts: ^4.0.4
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  confetti: ^0.7.0 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/home/logo.png
    - assets/banner.webp
    - assets/Intro/start.json
    - assets/Intro/start2.json
    - assets/Intro/start3.json
    - assets/
    - assets/register.json
  uses-material-design: true
